export const GenderOptions = ["male", "female", "other"];

export const APIServerURL ='https://doctorvisitapp-production.up.railway.app/api/v1'

export const catigoryList =[
  {
    name: "Dermatologist",
    value: "dermatologist",
    url: "/skin.png",
  },
  {
    name: "Allergist",
    value: "allergist",
    url: "/allergy.png",
  },
  {
    name: "Gastroenterologist",
    value: "gastroenterologist",
    url: "/Gastroenterologist.png",
  },
  {
    name: "Neurologist",
    value: "neurologist",
    url: "/neurologist.png",
  },
  {
    name: "Cardiology",
    value: "cardiology",
    url: "/cardiologist.png",
  },
  {
    name: "Gynecologist",
    value: "gynecologist",
    url: "/gynecologist.png",
  },
  {
    name: "Pediatrician",
    value: "pediatrician",
    url: "/pediatrician.png",
  },
  {
    name: "Hepatologist",
    value: "hepatologist",
    url: "/hepatologist.png",
  },
  {
    name: "Osteopathic",
    value: "osteopathic",
    url: "/osteopathic_.png",
  },
  {
    name: "Endocrinologist",
    value: "endocrinologist",
    url: "/endocrinologist.png",
  },
  {
    name: "Pulmonologist",
    value: "pulmonologist",
    url: "/pulmonologist.png",
  },
  {
    name: "Internal Medicine",
    value: "internal medicine",
    url: "/internal_medicine.png",
  },
  {
    name: "Common Cold",
    value: "common cold",
    url: "/common_cold.png",
  },
  {
    name: "Phlebologist",
    value: "phlebologist",
    url: "/phlebologist.png",
  },
  {
    name: "Osteoarthritis",
    value: "osteoarthritis",
    url: "/osteoarthritis.png",
  },
  {
    name: "Rheumatologists",
    value: "rheumatologists",
    url: "/rheumatologists.png",
  },
  {
    name: "Otolaryngologist",
    value: "otolaryngologist",
    url: "/otolaryngologist.png",
  },
];

export const doctorlist = [
  {
    uid: '1',
    url: "/beautiful-young-female-doctor-looking-camera-office.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "15 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
    patientId:"23",
    degrees:"master",
    specialty: "dermatologist"
  },
  {
    uid: '2',
    url: "/assets/doctors/1.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "10 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
    patientId:"23",
    degrees:"PHA",
    specialty: "allergist"
  },
  {
    uid: '3',
    url: "/assets/doctors/2.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "13 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
    patientId:"23",
    degrees:"master",
    specialty: "gastroenterologist"
  },
  {
    uid: '4',
    url: "/assets/doctors/3.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "11 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "rthopedics"
  },
  {
    uid: '5',
    url: "/assets/doctors/4.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "hepatologist"
  },
  {
    uid: '6',
    url: "/assets/doctors/5.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "9 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "orthopedics"
  },
  {
    uid: '7',
    url: "/assets/doctors/6.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "12 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "endocrinologist"
  },
  {
    uid: '8',
    url: "/assets/doctors/7.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "5 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "orthopedics"
  },
  {
    uid: '9',
    url: "/assets/doctors/8.avif",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "7 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "phlebologist"
  },
  {
    uid: '102',
    url: "/assets/doctors/9.avif",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "9 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "hepatologist"
  },
  {
    uid: '132',
    url: "/assets/doctors/10.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "4 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "otolaryngologist"
  },
  {
    uid: '12',
    url: "/assets/doctors/11.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "15 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "rheumatologists"
  },
  {
    uid: '13',
    url: "/assets/doctors/12.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "orthopedics"
  },
  {
    uid: '1135',
    url: "/assets/doctors/13.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "3 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "internal_medicine"
  },
  {
    uid: '1234',
    url: "/assets/doctors/14.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "orthopedics"
  },  {
    uid: '13984',
    url: "/beautiful-young-female-doctor-looking-camera-office.jpg",
    last_name:"",
    first_name: "Nore Ali",
    Year_of_Experience: "15 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "pediatrician"
  },
  {
    uid: '112',
    url: "/assets/doctors/1.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "10 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "internal_medicine"
  },
  {
    uid: '235',
    url: "/assets/doctors/2.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "13 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "radiology"
  },
  {
    uid: '1235',
    url: "/assets/doctors/3.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "11 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "osteoarthritis"
  },
  {
    uid: '230',
    url: "/assets/doctors/4.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "orthopedics"
  },
  {
    uid: '161',
    url: "/assets/doctors/5.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "9 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHA",
    specialty: "common_cold"
  },
  {
    uid: '171',
    url: "/assets/doctors/6.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "12 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "pediatrician"
  },
  {
    uid: '341',
    url: "/assets/doctors/7.jpg",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "5 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PCA",
    specialty: "orthopedics"
  },
  {
    uid: '4231',
    url: "/assets/doctors/8.avif",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "7 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "pediatrician"
  },
  {
    uid: '5641',
    url: "/assets/doctors/9.avif",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "9 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"BHD",
    specialty: "common_cold"
  },
  {
    uid: '2341',
    url: "/assets/doctors/10.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "4 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"PHD",
    specialty: "osteoarthritis"
  },
  {
    uid: '4361',
    url: "/assets/doctors/11.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "15 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "common_cold"
  },
  {
    uid: '3461',
    url: "/assets/doctors/12.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "orthopedics"
  },
  {
    uid: '341',
    url: "/assets/doctors/13.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "3 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "common_cold"
  },
  {
    uid: '561',
    url: "/assets/doctors/14.png",
    last_name:"",
    first_name: "Mohammed Ali",
    Year_of_Experience: "8 Years",
    location: "Cairo",
    feePerCunsultation:"600",
    About:"asikdfmnl;iwamokpofjijj",
    Suggestions:[],
     patientId:"23",
    degrees:"master",
    specialty: "osteoarthritis"
  },
]

export const PatientFormDefaultValues = {
  name:"",
  email: "",
  phone: "",
  birthDate: new Date(Date.now()),
  gender: "male" as Gender,
  location: "",
  occupation: "",
  emergencyContactName: "",
  emergencyContactNumber: "",
  primaryPhysician: "",
  insuranceProvider: "",
  insurancePolicyNumber: "",
  allergies: "",
  currentMedication: "",
  familyMedicalHistory: "",
  pastMedicalHistory: "",
  identificationType: "Birth Certificate",
  identificationNumber: "",
  identificationDocument: [],
  treatmentConsent: false,
  disclosureConsent: false,
  privacyConsent: false,
};

export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Resident Alien Card (Green Card)",
  "Social Security Card",
  "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const Doctors = [
  {
    image: "/assets/images/dr-green.png",
    name: "John Green",
  },
  {
    image: "/assets/images/dr-cameron.png",
    name: "Leila Cameron",
  },
  {
    image: "/assets/images/dr-livingston.png",
    name: "David Livingston",
  },
  {
    image: "/assets/images/dr-peter.png",
    name: "Evan Peter",
  },
  {
    image: "/assets/images/dr-powell.png",
    name: "Jane Powell",
  },
  {
    image: "/assets/images/dr-remirez.png",
    name: "Alex Ramirez",
  },
  {
    image: "/assets/images/dr-lee.png",
    name: "Jasmine Lee",
  },
  {
    image: "/assets/images/dr-cruz.png",
    name: "Alyana Cruz",
  },
  {
    image: "/assets/images/dr-sharma.png",
    name: "Hardik Sharma",
  },
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  cancelled: "/assets/icons/cancelled.svg",
};